#!/usr/bin/bash 

rm -rf ./bin
mkdir bin

# compile main
cmd="gcc -Wall -std=c99 -pedantic -o ./bin/main main.c"

printf "building \n\t ${cmd}\n"
eval $cmd

echo "executing bin/main"

eval "./bin/main"
